spring:
    datasource:
        platform: mysql
        url: jdbc:mysql://127.0.0.1:3306/comiread
        username: root
        password:
    jpa:
        hibernate:
            ddl-auto: update
        database: mysql
        show-sql: true
